# Generated by Django 5.0.1 on 2024-01-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('symbol', models.CharField(default='missing', max_length=100)),
                ('name', models.CharField(default='missing', max_length=100)),
                ('image', models.CharField(default='missing', max_length=100)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('market_cap_rank', models.IntegerField(blank=True, null=True)),
                ('fully_diluted_valuation', models.BigIntegerField(blank=True, null=True)),
                ('total_volume', models.BigIntegerField(blank=True, null=True)),
                ('high_24h', models.BigIntegerField(blank=True, null=True)),
                ('low_24h', models.BigIntegerField(blank=True, null=True)),
                ('price_change_24h', models.FloatField(blank=True, null=True)),
                ('price_change_percentage_24h', models.FloatField(blank=True, null=True)),
                ('market_cap_change_24h', models.FloatField(blank=True, null=True)),
                ('circulating_supply', models.BigIntegerField(blank=True, null=True)),
                ('total_supply', models.BigIntegerField(blank=True, null=True)),
                ('max_supply', models.BigIntegerField(blank=True, null=True)),
                ('ath', models.BigIntegerField(blank=True, null=True)),
                ('ath_change_percentage', models.FloatField(blank=True, null=True)),
                ('atl', models.FloatField(blank=True, null=True)),
                ('atl_change_percentage', models.FloatField(blank=True, null=True)),
                ('roi', models.CharField(default='missing', max_length=100)),
                ('price_change_percentage_1h_in_currency', models.FloatField(blank=True, null=True)),
                ('price_change_percentage_24h_in_currency', models.FloatField(blank=True, null=True)),
                ('price_change_percentage_7d_in_currency', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
