# Generated by Django 5.0.1 on 2024-01-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_coin_ath_date_coin_atl_date_coin_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
