# Generated by Django 5.0.1 on 2024-01-21 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_coin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='coin',
            name='roi',
            field=models.CharField(blank=True, default='missing', max_length=100, null=True),
        ),
    ]
